target 'ALWAppResourcesManager_Example' do
  pod 'ALWAppResourcesManager', :path => '../', :subspecs => ['Core', 'WebP', 'MainProject']

  target 'ALWAppResourcesManager_Tests' do
    use_frameworks!

    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
