use_frameworks!

target 'ALWAppResourcesManager_Example' do
  pod 'ALWAppResourcesManager', :path => '../'

  target 'ALWAppResourcesManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
